name: Release

on:
  push:
    branches: [main]

jobs:
  docker-python:
    strategy:
      matrix:
        python-version:
          - 3.11.2-slim-bullseye
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: python/Dockerfile
          ignore: DL3008
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/quicklytics-io/python
          tags: |
            # full length sha
            type=sha,format=long,prefix=
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ matrix.python-version }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMG_VERSION=${{ matrix.python-version }}
          context: python
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
