name: Release

on:
  push:
    branches: [main]

jobs:
  base-images:
    strategy:
      matrix:
        lang_and_version:
          - python|3.11.2-slim-bullseye
          - ruby|3.2.2-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: '|'
          maxsplit: 1
          msg: ${{ matrix.lang_and_version }}
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ steps.split.outputs._0 }}/Dockerfile
          ignore: DL3008
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/quicklytics-io/${{ steps.split.outputs._0 }}
          tags: |
            # full length sha
            type=sha,format=long,prefix=
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.split.outputs._1 }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_IMG_VERSION=${{ steps.split.outputs._1 }}
          context: ${{ steps.split.outputs._0 }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  utils:
    needs: base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        util_name:
          - pgslice
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: utils/${{ matrix.util_name }}/Dockerfile
          ignore: DL3008
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/quicklytics-io/${{ matrix.util_name }}
          flavor: |
            latest=true
          tags: |
            # full length sha
            type=sha,format=long,prefix=
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: utils/${{ matrix.util_name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
