name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  base-images:
    strategy:
      fail-fast: false
      matrix:
        lang_and_version:
          - python|3.11.2-slim-bullseye
          - ruby|3.2.3-slim
          - ruby|3.3.0-slim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: '|'
          maxsplit: 1
          msg: ${{ matrix.lang_and_version }}
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ steps.split.outputs._0 }}/Dockerfile
          ignore: DL3008
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/quicklytics-io/${{ steps.split.outputs._0 }}
          tags: |
            # full length sha
            type=sha,format=long,prefix=
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ steps.split.outputs._1 }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BASE_IMG_VERSION=${{ steps.split.outputs._1 }}
          context: ${{ steps.split.outputs._0 }}
          push: true
          cache-from: type=gha,scope=${{ matrix.lang_and_version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.lang_and_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
  utils:
    needs: base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: pgslice
            version: 0.6.1
          - name: odbc2parquet
            version: 4.1.2
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: utils/${{ matrix.name }}/Dockerfile
          ignore: DL3008
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/quicklytics-io/${{ matrix.name }}
          flavor: |
            latest=true
          tags: |
            # full length sha
            type=sha,format=long,prefix=
            type=raw,enable=true,priority=200,prefix=,suffix=,value=${{ matrix.version }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: utils/${{ matrix.name }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            TOOL_VERSION=${{ matrix.version }}
          push: true
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
